---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
baseurl: "https://michael-brown.net/"
title: "Michael Brown"
paginate: 5
copyright: "Copyright © 2016"
canonifyurls: true
theme: "casper"
metaDataFormat: "yaml"

params:
  description: "the only way to do great work is to love what you do"
  cover: "images/bridge2.jpg"
  author: "Michael Brown"
  # authorlocation: "Lisbon, Portugal"
  authorwebsite: "https://michael-brown.net"
  noauthor: false
  share: false
  # bio: "iOS Developer"
  logo: "images/head.png"
  googleAnalyticsUserID: "UA-41132207-2"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink: "https://feeds.feedburner.com/..."
  githubName: "mluisbrown"
  twitterName: "mluisbrown"
  stackoverflowId: "368085"
  # facebookName: ""
  # linkedinName: ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport: false
  hjsStyle: "github"

permalinks:
  post: "/:year/:slug/"

menu:
  main:
  - identifier: "blog"
    name: "Blog"
    url: "/"
    weight: -120
...
