name = "Casper"
license = "MIT"
licenselink = "https://github.com/vjeantet/hugo-theme-casper/blob/master/LICENSE.md"
description = "Casper theme from Ghost Foundation"
homepage = "https://vjeantet.fr/"
tags = ["blog"]
features = ["disqus", "google analytics","share"]
min_version=0.25

[author]
  name = "Valere JEANTET"
  homepage = "https://vjeantet.fr"

[original]
  name = "Casper"
  homepage = "https://github.com/TryGhost/Casper"
  repo = "https://github.com/TryGhost/Casper"
